test: Add op= scoping rules tests
These test the special op= scoping rules where a variable on the LHS
must be declared in-scope.

Signed-off-by: Keith Packard <keithp@keithp.com>

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -14,7 +14,7 @@
 
 SNEK?=../posix/snek
 
-TESTS = \
+SUCCESS_TESTS = \
 	andor.py \
 	list.py \
 	dict.py \
@@ -33,11 +33,16 @@ TESTS = \
 	slice.py \
 	while.py \
 	while-break.py \
-	while-else.py
+	while-else.py \
+	scoping-global.py \
+	scoping-local.py
+
+FAIL_TESTS = \
+	scoping-no-decl.py
 
 check:
 	@exit=0; \
-	for TEST in $(TESTS); do \
+	for TEST in $(SUCCESS_TESTS); do \
 		echo "Running test $$TEST."; \
 		if python3 $$TEST; then \
 			echo "    python pass"; \
@@ -46,6 +51,23 @@ check:
 			exit=1; \
 		fi; \
 		if $(SNEK) $$TEST; then \
+			echo "    snek pass"; \
+		else \
+			echo "    ***************** snek fail ***********************"; \
+			exit=1; \
+		fi; \
+	done; \
+	for TEST in $(FAIL_TESTS); do \
+		echo "Running test $$TEST."; \
+		python3 $$TEST; \
+		if [ $$? -eq 1 ]; then \
+			echo "    python pass"; \
+		else \
+			echo "    ***************** python fail *********************"; \
+			exit=1; \
+		fi; \
+		$(SNEK) $$TEST; \
+		if [ $$? -eq 1 ]; then \
 			echo "    snek pass"; \
 		else \
 			echo "    ***************** snek fail ***********************"; \
